name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required to check out the code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-hdbk-iac
          template: ./infra/bicep/main.bicep
          parameters: ./infra/bicep/main.parameters.json
          failOnStdErr: false
